# Generated by Django 2.1 on 2018-09-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_valid',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='is_valid',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='publish',
            name='is_valid',
            field=models.IntegerField(default=1),
        ),
    ]
